branches:
  except:
    - /^[0-9]/
language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y cmake libboost-dev libboost-thread-dev libboost-system-dev libsqlite3-dev subversion curl libcurl4-openssl-dev libusb-dev zlib1g-dev libudev-dev
  - svn co http://open-zwave.googlecode.com/svn/trunk/ open-zwave-read-only
script:
  - (cd open-zwave-read-only; make)
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_LIBRARY_PATH=open-zwave-read-only
  - make
before_deploy:
  - tar czf domoticz_${TRAVIS_BUILD_NUMBER}.tgz domoticz History.txt License.txt svnversion.h domoticz.sh --exclude .git www/ scripts/ Config/
deploy:
  provider: releases
  api-key:
    secure: TBH9KopK/4nAe/AGCkd6jV82t3aCREpHLAiaGAG9m22wfKIvo3YxvSXcH8iaQWLWBEKlRzYCQorx650vR22aQiiJwYlaRnhnVM1IAKMIImY5Aw4+r7fKUCPERCVkkPikMIxJwWZkGanVfJiGir9gLrwSFLzy3DRXPVNRPS2uHUk=
  file: domoticz_${TRAVIS_BUILD_NUMBER}.tgz
  skip_cleanup: true
  on:
    tags: true
    all_branches: true